vimc-4457: Add bundle pack/import for remotes
vimc/orderly pull request #258
Opened 2020-12-07 18:09 UTC by richfitz

This PR completes the remote support for bundles, by adding two new functions to orderly for packing and importing from a remote.

2020-12-08 14:33 UTC, mwoodbri requested changes
I haven't run this code but it looks essentially good to my (relatively) untrained eye. Just a couple of typos and a seemingly unused variable that could tidied up.

2020-12-08 14:33 UTC, mwoodbri commented on R/bundle.R
> +##'   (a zip file created by \code{orderly_bundle_run}}
```suggestion
##'   (a zip file created by \code{orderly_bundle_run})}
```

2020-12-08 14:33 UTC, mwoodbri commented on R/remote.R
> +##' extract a long-running report from a server to run (say) on a HPC
```suggestion
##' extract a long-running report from a server to run (say) on an HPC
```

2020-12-08 14:33 UTC, mwoodbri commented on R/remote.R
> +##'    be run fro the system where the bundle will be run (an HPC
```suggestion
##'    be run from the system where the bundle will be run (an HPC
```

2020-12-08 14:33 UTC, mwoodbri commented on R/remote.R
> +##'    head-node or a other powerful computer).
```suggestion
##'    head-node or another powerful computer).
```

2020-12-08 14:33 UTC, mwoodbri commented on tests/testthat/test-remote-path.R
> +  path2 <- prepare_orderly_example("minimal")
Unused

2020-12-08 14:55 UTC, richfitz commented on tests/testthat/test-remote-path.R
> +  path2 <- prepare_orderly_example("minimal")
thanks, removed now

2020-12-10 12:06 UTC, r-ash approved these changes
Nice, this looks really useful

2020-12-10 12:08 UTC, mwoodbri approved these changes

2020-12-10 12:11 UTC, merged