MRC-2321: max-depth arg to orderly_graph now limits depth of tree returned
vimc/orderly pull request #278
Opened 2021-04-13 14:15 UTC by r-ash

instead of throwing an error

2021-04-13 14:45 UTC, r-ash commented on tests/testthat/test-dependency.R
> +test_that("dependency latest with search query", {
Added this test too to convince myself that this is how it is working, figured it would be generally useful as I don't think this case is covered

2021-04-14 08:07 UTC, richfitz requested changes
thanks - looks good aside from two extremely minor things

2021-04-14 08:07 UTC, richfitz commented on NEWS.md
> +* `orderly_graph` arg `max_depth` now truncates depth of the tree instead of throwing error and arg `recursion_depth` added which works how `max_depth` used to
this should be `recursion_limit`

2021-04-14 08:07 UTC, richfitz commented on R/dependencies.R
> +                          max_depth = 100, recursion_limit = 100,
default for max_depth should be Inf I think

2021-04-14 09:52 UTC, r-ash commented on NEWS.md
> +* `orderly_graph` arg `max_depth` now truncates depth of the tree instead of throwing error and arg `recursion_depth` added which works how `max_depth` used to
oops, thanks!

2021-04-14 10:21 UTC, richfitz approved these changes

2021-04-14 10:21 UTC, merged